// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  FIREBASE_CONFIG : {
    apiKey: "AIzaSyCYaZAKyUw6LrzUls3FWXiJlb2UxCHRHfM",
    authDomain: "gatolin-da5cb.firebaseapp.com",
    projectId: "gatolin-da5cb",
    storageBucket: "gatolin-da5cb.appspot.com",
    messagingSenderId: "1071314589359",
    appId: "1:1071314589359:web:14cd02dc5ab0276ddda65a"
  },
  AUTH_ERROR_CODES : {
    "auth/email-already-exists" : "Otro usuario ya está utilizando el correo electrónico proporcionado. Cada usuario debe tener un correo electrónico único",
    "auth/id-token-expired" : "El token de ID de Firebase que se proporcionó está vencido",
    "auth/id-token-revoked" : "Se revocó el token de ID de Firebase",
    "auth/invalid-login-credentials" : "Credenciales de inicio de sesión inválidas",
    "auth/admin-restricted-operation": "Operación restringida",
    "auth/argument-error": "Error de argumento",
    "auth/app-not-authorized": "Aplicación no autorizada",
    "auth/app-not-installed": "Aplicación no instalada",
    "auth/captcha-check-failed": "Verificación de CAPTCHA fallida",
    "auth/code-expired": "Código expirado",
    "auth/cordova-not-ready": "Cordova no está listo",
    "auth/cors-unsupported": "CORS no es compatible",
    "auth/credential-already-in-use": "Credencial ya en uso",
    "auth/custom-token-mismatch": "Token personalizado no coincide",
    "auth/requires-recent-login": "Requiere inicio de sesión reciente",
    "auth/dependent-sdk-initialized-before-auth": "SDK dependiente inicializado antes de la autenticación",
    "auth/dynamic-link-not-activated": "Enlace dinámico no activado",
    "auth/email-change-needs-verification": "El cambio de correo electrónico necesita verificación",
    "auth/email-already-in-use": "Correo electrónico ya en uso",
    "auth/emulator-config-failed": "Configuración del emulador fallida",
    "auth/expired-action-code": "Código de acción expirado",
    "auth/cancelled-popup-request": "Solicitud de ventana emergente cancelada por el usuario",
    "auth/internal-error": "Error interno",
    "auth/invalid-api-key": "Clave de API no válida",
    "auth/invalid-app-credential": "Credencial de aplicación no válida",
    "auth/invalid-app-id": "ID de aplicación no válido",
    "auth/invalid-user-token": "Token de usuario no válido",
    "auth/invalid-auth-event": "Evento de autenticación no válido",
    "auth/invalid-cert-hash": "Hash de certificado no válido",
    "auth/invalid-verification-code": "Código de verificación no válido",
    "auth/invalid-continue-uri": "URI de continuación no válido",
    "auth/invalid-cordova-configuration": "Configuración de Cordova no válida",
    "auth/invalid-custom-token": "Token personalizado no válido",
    "auth/invalid-dynamic-link-domain": "Dominio de enlace dinámico no válido",
    "auth/invalid-email": "Correo electrónico no válido",
    "auth/invalid-emulator-scheme": "Esquema de emulador no válido",
    "auth/invalid-credential": "Credencial no válida",
    "auth/invalid-message-payload": "Carga útil de mensaje no válida",
    "auth/invalid-multi-factor-session": "Sesión de múltiples factores no válida",
    "auth/invalid-oauth-client-id": "ID de cliente de OAuth no válido",
    "auth/invalid-oauth-provider": "Proveedor de OAuth no válido",
    "auth/invalid-action-code": "Código de acción no válido",
    "auth/unauthorized-domain": "Dominio no autorizado",
    "auth/wrong-password": "Contraseña incorrecta",
    "auth/invalid-persistence-type": "Tipo de persistencia no válido",
    "auth/invalid-phone-number": "Número de teléfono no válido",
    "auth/invalid-provider-id": "ID de proveedor no válido",
    "auth/invalid-recipient-email": "Correo electrónico del destinatario no válido",
    "auth/invalid-sender": "Remitente no válido",
    "auth/invalid-verification-id": "ID de verificación no válido",
    "auth/invalid-tenant-id": "ID de inquilino no válido",
    "auth/multi-factor-info-not-found": "Información de múltiples factores no encontrada",
    "auth/multi-factor-auth-required": "Autenticación de múltiples factores requerida",
    "auth/missing-android-pkg-name": "Falta el nombre del paquete de Android",
    "auth/missing-app-credential": "Falta la credencial de la aplicación",
    "auth/auth-domain-config-required": "Se requiere configuración de dominio de autenticación",
    "auth/missing-verification-code": "Falta el código de verificación",
    "auth/missing-continue-uri": "Falta el URI de continuación",
    "auth/missing-iframe-start": "Falta el inicio del iframe",
    "auth/missing-ios-bundle-id": "Falta el ID de paquete de iOS",
    "auth/missing-or-invalid-nonce": "Falta o es inválido el nonce",
    "auth/missing-multi-factor-info": "Falta información de múltiples factores",
    "auth/missing-multi-factor-session": "Falta sesión de múltiples factores",
    "auth/missing-phone-number": "Falta el número de teléfono",
    "auth/missing-verification-id": "Falta el ID de verificación",
    "auth/app-deleted": "Aplicación eliminada",
    "auth/account-exists-with-different-credential": "Cuenta existe con credenciales diferentes",
    "auth/network-request-failed": "Solicitud de red fallida",
    "auth/null-user": "Usuario nulo",
    "auth/no-auth-event": "Sin evento de autenticación",
    "auth/no-such-provider": "Proveedor no existe",
    "auth/operation-not-allowed": "Operación no permitida",
    "auth/operation-not-supported-in-this-environment": "Operación no compatible en este entorno",
    "auth/popup-blocked": "Bloqueo de ventana emergente",
    "auth/popup-closed-by-user": "Ventana emergente cerrada por el usuario",
    "auth/provider-already-linked": "Proveedor ya vinculado",
    "auth/quota-exceeded": "Cuota excedida",
    "auth/redirect-cancelled-by-user": "Redirección cancelada por el usuario",
    "auth/redirect-operation-pending": "Operación de redirección pendiente",
    "auth/rejected-credential": "Credencial rechazada",
    "auth/second-factor-already-in-use": "Segundo factor ya en uso",
    "auth/maximum-second-factor-count-exceeded": "Se excedió el recuento máximo de segundos factores",
    "auth/tenant-id-mismatch": "Incompatibilidad de ID de inquilino",
    "auth/timeout": "Tiempo de espera",
    "auth/user-token-expired": "Token de usuario expirado",
    "auth/too-many-requests": "Demasiadas solicitudes, inténtalo más tarde",
    "auth/unauthorized-continue-uri": "URI de continuación no autorizado",
    "auth/unsupported-first-factor": "Primer factor no compatible",
    "auth/unsupported-persistence-type": "Tipo de persistencia no compatible",
    "auth/unsupported-tenant-operation": "Operación no compatible con inquilino",
    "auth/unverified-email": "Correo electrónico no verificado",
    "auth/user-cancelled": "Usuario cancelado",
    "auth/user-not-found": "Usuario no encontrado",
    "auth/user-disabled": "Usuario deshabilitado",
    "auth/user-mismatch": "Usuario no coincide",
    "auth/user-signed-out": "Usuario cerró sesión",
    "auth/weak-password": "Contraseña débil",
    "auth/web-storage-unsupported": "Almacenamiento web no compatible",
    "auth/already-initialized": "Ya inicializado",
    "auth/recaptcha-not-enabled": "reCAPTCHA no habilitado",
    "auth/missing-recaptcha-token": "Falta el token de reCAPTCHA",
    "auth/invalid-recaptcha-token": "Token de reCAPTCHA no válido",
    "auth/invalid-recaptcha-action": "Acción de reCAPTCHA no válida",
    "auth/missing-client-type": "Falta el tipo de cliente",
    "auth/missing-recaptcha-version": "Falta la versión de reCAPTCHA",
    "auth/invalid-recaptcha-version": "Versión de reCAPTCHA no válida",
    "auth/invalid-req-type": "Tipo de solicitud no válido",
  },
  FACE_APP_ID : 1372240503720494,
  DRIVE_URL: "https://drive.google.com/uc?export=download&id="
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
